version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: lanchesdatia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: lanchesdatia_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede:
          driver: bridge 
      